// All cocktails — migrated from frontend COCKTAILS array
// recipe[].is_garnish = true means the ingredient is garnish-only (not required for makability)
module.exports = [
  { name:"Old Fashioned", popularity:1, glass:"Rocks glass", method:"Stir",
    steps:"Muddle sugar with bitters and a splash of water. Add bourbon and a large ice cube. Stir 25 seconds. Express and drop in the orange peel.",
    recipe:[{amount:"2 oz",ingredient:"Bourbon",is_garnish:false},{amount:"2 dashes",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 cube",ingredient:"Sugar",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Martini", popularity:2, glass:"Martini glass", method:"Stir",
    steps:"Stir gin and vermouth with ice 30 seconds. Strain into a chilled coupe. Garnish with olives on a pick.",
    recipe:[{amount:"2½ oz",ingredient:"Gin",is_garnish:false},{amount:"½ oz",ingredient:"Dry vermouth",is_garnish:false},{amount:"2",ingredient:"Olives",is_garnish:true}]},
  { name:"Negroni", popularity:3, glass:"Rocks glass", method:"Stir",
    steps:"Build in a rocks glass over a large ice cube. Stir gently. Garnish with an orange peel twist.",
    recipe:[{amount:"1 oz",ingredient:"Gin",is_garnish:false},{amount:"1 oz",ingredient:"Campari",is_garnish:false},{amount:"1 oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Margarita", popularity:4, glass:"Coupe or rocks", method:"Shake",
    steps:"Salt-rim the glass. Shake all ingredients with ice 12 seconds. Strain over fresh ice or into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"1 oz",ingredient:"Triple sec / Cointreau",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"pinch",ingredient:"Salt (rim)",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Daiquiri", popularity:5, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients vigorously with ice 15 seconds. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Mojito", popularity:6, glass:"Highball", method:"Build",
    steps:"Gently muddle mint with lime juice and syrup. Add rum and ice, stir. Top with soda water. Garnish with a mint sprig.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"8–10 leaves",ingredient:"Fresh mint",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 sprig",ingredient:"Mint",is_garnish:true}]},
  { name:"Whiskey Sour", popularity:7, glass:"Rocks glass", method:"Shake",
    steps:"Dry shake all ingredients 15 seconds. Add ice and shake again 10 seconds. Strain over ice. Top the foam with Angostura dashes.",
    recipe:[{amount:"2 oz",ingredient:"Bourbon",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false}]},
  { name:"Manhattan", popularity:8, glass:"Coupe", method:"Stir",
    steps:"Stir all ingredients with ice 30 seconds. Strain into a chilled coupe. Garnish with a brandied cherry.",
    recipe:[{amount:"2 oz",ingredient:"Rye whiskey",is_garnish:false},{amount:"1 oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"2 dashes",ingredient:"Angostura bitters",is_garnish:false},{amount:"1",ingredient:"Brandied cherry",is_garnish:true}]},
  { name:"Espresso Martini", popularity:9, glass:"Martini glass", method:"Shake",
    steps:"Shake all ingredients hard with ice 15 seconds for a thick froth. Double strain into a chilled martini glass. Garnish with 3 coffee beans.",
    recipe:[{amount:"1½ oz",ingredient:"Vodka",is_garnish:false},{amount:"¾ oz",ingredient:"Coffee liqueur",is_garnish:false},{amount:"1 oz",ingredient:"Fresh espresso (cooled)",is_garnish:false},{amount:"3",ingredient:"Coffee beans",is_garnish:true}]},
  { name:"Aperol Spritz", popularity:10, glass:"Wine glass", method:"Build",
    steps:"Fill a large wine glass with ice. Pour prosecco, then Aperol, then soda. Stir gently. Garnish with a half-orange slice.",
    recipe:[{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"2 oz",ingredient:"Aperol",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"½ slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Moscow Mule", popularity:11, glass:"Copper mug", method:"Build",
    steps:"Fill a copper mug with ice. Add vodka and lime juice. Top with ginger beer. Garnish with a lime wheel and mint.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Ginger beer",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true},{amount:"1 sprig",ingredient:"Mint",is_garnish:true}]},
  { name:"Dark & Stormy", popularity:12, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Pour ginger beer and lime juice. Float dark rum on top by pouring over a spoon.",
    recipe:[{amount:"2 oz",ingredient:"Dark rum (Gosling's)",is_garnish:false},{amount:"4 oz",ingredient:"Ginger beer",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Gin & Tonic", popularity:13, glass:"Highball or copa", method:"Build",
    steps:"Fill a highball or copa with ice. Add gin, then tonic slowly to preserve fizz. Squeeze in lime and drop in.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Paloma", popularity:14, glass:"Highball", method:"Build",
    steps:"Salt-rim a highball. Fill with ice. Add tequila, grapefruit juice, lime, and salt. Top with soda water.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"2 oz",ingredient:"Fresh grapefruit juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"pinch",ingredient:"Salt",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 wedge",ingredient:"Grapefruit",is_garnish:true}]},
  { name:"Cosmopolitan", popularity:15, glass:"Martini glass", method:"Shake",
    steps:"Shake all ingredients with ice 10 seconds. Strain into a chilled martini glass. Garnish with a flamed orange peel.",
    recipe:[{amount:"1½ oz",ingredient:"Citrus vodka",is_garnish:false},{amount:"½ oz",ingredient:"Triple sec / Cointreau",is_garnish:false},{amount:"½ oz",ingredient:"Cranberry juice",is_garnish:false},{amount:"¼ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Pornstar Martini", popularity:16, glass:"Martini glass", method:"Shake",
    steps:"Shake vodka, liqueur, juice, and syrup with ice. Double strain into a martini glass. Garnish with half a passion fruit. Serve a side shot of prosecco.",
    recipe:[{amount:"1½ oz",ingredient:"Vanilla vodka",is_garnish:false},{amount:"¾ oz",ingredient:"Passion fruit liqueur (Passoa)",is_garnish:false},{amount:"¾ oz",ingredient:"Passion fruit purée",is_garnish:false},{amount:"½ oz",ingredient:"Vanilla syrup",is_garnish:false},{amount:"1 oz",ingredient:"Prosecco (side shot)",is_garnish:false},{amount:"½",ingredient:"Passion fruit",is_garnish:true}]},
  { name:"Sex on the Beach", popularity:17, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and peach schnapps. Pour orange juice and cranberry juice to create a layered effect.",
    recipe:[{amount:"1½ oz",ingredient:"Vodka",is_garnish:false},{amount:"1 oz",ingredient:"Peach schnapps",is_garnish:false},{amount:"2 oz",ingredient:"Orange juice",is_garnish:false},{amount:"2 oz",ingredient:"Cranberry juice",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Piña Colada", popularity:18, glass:"Hurricane glass", method:"Blend",
    steps:"Blend all ingredients with 1 cup crushed ice until smooth. Pour into a hurricane glass. Garnish with a pineapple wedge and cherry.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"1½ oz",ingredient:"Coconut cream",is_garnish:false},{amount:"3 oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"1 wedge",ingredient:"Pineapple",is_garnish:true}]},
  { name:"Rum & Coke", popularity:19, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add rum then cola. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Dark rum",is_garnish:false},{amount:"4 oz",ingredient:"Cola",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Vodka Soda", popularity:20, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and lime juice. Top with soda water. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Soda water",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Tom Collins", popularity:21, glass:"Highball", method:"Build",
    steps:"Shake gin, lemon, and syrup briefly with ice. Strain into an ice-filled highball. Top with soda water.",
    recipe:[{amount:"2 oz",ingredient:"Gin (London Dry)",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Lemon",is_garnish:true}]},
  { name:"French 75", popularity:22, glass:"Champagne flute", method:"Shake",
    steps:"Shake gin, lemon, and syrup with ice. Strain into a flute. Top with champagne.",
    recipe:[{amount:"1½ oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"2 oz",ingredient:"Champagne",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Sidecar", popularity:23, glass:"Coupe", method:"Shake",
    steps:"Sugar the rim. Shake all ingredients with ice. Double strain into the prepared coupe.",
    recipe:[{amount:"1½ oz",ingredient:"Cognac",is_garnish:false},{amount:"¾ oz",ingredient:"Triple sec / Cointreau",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Jungle Bird", popularity:24, glass:"Rocks glass", method:"Shake",
    steps:"Shake all ingredients with ice. Strain into a rocks glass over ice.",
    recipe:[{amount:"1½ oz",ingredient:"Dark rum (Jamaican)",is_garnish:false},{amount:"¾ oz",ingredient:"Campari",is_garnish:false},{amount:"1½ oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"½ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1 wedge",ingredient:"Pineapple",is_garnish:true}]},
  { name:"Last Word", popularity:25, glass:"Coupe", method:"Shake",
    steps:"Combine equal parts in a shaker with ice. Shake vigorously. Strain into a chilled coupe.",
    recipe:[{amount:"¾ oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Green Chartreuse",is_garnish:false},{amount:"¾ oz",ingredient:"Maraschino liqueur (Luxardo)",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false}]},
  { name:"Paper Plane", popularity:26, glass:"Coupe", method:"Shake",
    steps:"Combine equal parts in a shaker with ice. Shake hard. Strain into a chilled coupe.",
    recipe:[{amount:"¾ oz",ingredient:"Bourbon",is_garnish:false},{amount:"¾ oz",ingredient:"Aperol",is_garnish:false},{amount:"¾ oz",ingredient:"Amaro Nonino",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false}]},
  { name:"Amaretto Sour", popularity:27, glass:"Rocks glass", method:"Shake",
    steps:"Dry shake all ingredients 15 seconds. Add ice and shake again. Strain over a large ice cube.",
    recipe:[{amount:"2 oz",ingredient:"Amaretto (Disaronno)",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¼ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false},{amount:"1",ingredient:"Brandied cherry",is_garnish:true}]},
  { name:"Tequila Sunrise", popularity:28, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add tequila then OJ. Slowly pour grenadine down the inside — it sinks for the sunrise effect. Do not stir.",
    recipe:[{amount:"2 oz",ingredient:"Tequila",is_garnish:false},{amount:"4 oz",ingredient:"Orange juice",is_garnish:false},{amount:"½ oz",ingredient:"Grenadine",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Boulevardier", popularity:29, glass:"Rocks glass", method:"Stir",
    steps:"Stir in a mixing glass with ice 30 seconds. Strain over a large ice cube.",
    recipe:[{amount:"1½ oz",ingredient:"Bourbon",is_garnish:false},{amount:"1 oz",ingredient:"Campari",is_garnish:false},{amount:"1 oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"White Russian", popularity:30, glass:"Rocks glass", method:"Build",
    steps:"Fill a rocks glass with ice. Add vodka and coffee liqueur. Float cream over the back of a spoon on top.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"1 oz",ingredient:"Coffee liqueur",is_garnish:false},{amount:"1 oz",ingredient:"Heavy cream (floated)",is_garnish:false}]},
  { name:"Black Russian", popularity:31, glass:"Rocks glass", method:"Build",
    steps:"Fill a rocks glass with ice. Add vodka and coffee liqueur. Stir briefly.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"1 oz",ingredient:"Coffee liqueur",is_garnish:false}]},
  { name:"Screwdriver", popularity:32, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and OJ. Stir.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"5 oz",ingredient:"Fresh orange juice",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Harvey Wallbanger", popularity:33, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and OJ. Float Galliano on top over a spoon.",
    recipe:[{amount:"1½ oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Orange juice",is_garnish:false},{amount:"½ oz",ingredient:"Galliano (float)",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Long Island Iced Tea", popularity:34, glass:"Highball", method:"Build",
    steps:"Shake all spirits, lemon, and syrup with ice. Strain into an ice-filled highball. Top with a splash of cola.",
    recipe:[{amount:"½ oz",ingredient:"Vodka",is_garnish:false},{amount:"½ oz",ingredient:"White rum",is_garnish:false},{amount:"½ oz",ingredient:"Tequila",is_garnish:false},{amount:"½ oz",ingredient:"Gin",is_garnish:false},{amount:"½ oz",ingredient:"Triple sec",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"splash",ingredient:"Cola",is_garnish:false},{amount:"1 wedge",ingredient:"Lemon",is_garnish:true}]},
  { name:"Singapore Sling", popularity:35, glass:"Highball", method:"Shake",
    steps:"Shake all ingredients with ice. Strain into an ice-filled highball.",
    recipe:[{amount:"1½ oz",ingredient:"Gin",is_garnish:false},{amount:"½ oz",ingredient:"Cherry Heering",is_garnish:false},{amount:"¼ oz",ingredient:"Triple sec",is_garnish:false},{amount:"¼ oz",ingredient:"Bénédictine",is_garnish:false},{amount:"½ oz",ingredient:"Grenadine",is_garnish:false},{amount:"4 oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 dash",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 wedge",ingredient:"Pineapple",is_garnish:true}]},
  { name:"Bloody Mary", popularity:36, glass:"Highball", method:"Build",
    steps:"Combine all ingredients in a shaker without ice and roll (pour back and forth) to mix. Pour over ice in a highball.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Tomato juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"2 dashes",ingredient:"Worcestershire sauce",is_garnish:false},{amount:"2 dashes",ingredient:"Hot sauce",is_garnish:false},{amount:"1 tsp",ingredient:"Horseradish",is_garnish:false},{amount:"pinch",ingredient:"Celery salt & black pepper",is_garnish:false},{amount:"1 stalk",ingredient:"Celery",is_garnish:true}]},
  { name:"Clover Club", popularity:37, glass:"Coupe", method:"Shake",
    steps:"Dry shake all ingredients. Add ice and shake again. Double strain into a chilled coupe. Garnish with fresh raspberries.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Raspberry syrup",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false}]},
  { name:"Gimlet", popularity:38, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients with ice. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Bee's Knees", popularity:39, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients vigorously with ice. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Honey syrup (2:1 honey:water)",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Aviation", popularity:40, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients with ice. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"½ oz",ingredient:"Maraschino liqueur",is_garnish:false},{amount:"¼ oz",ingredient:"Crème de violette",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"1",ingredient:"Cherry",is_garnish:true}]},
  { name:"Naked and Famous", popularity:41, glass:"Coupe", method:"Shake",
    steps:"Combine equal parts in a shaker with ice. Shake well. Strain into a chilled coupe.",
    recipe:[{amount:"¾ oz",ingredient:"Mezcal",is_garnish:false},{amount:"¾ oz",ingredient:"Aperol",is_garnish:false},{amount:"¾ oz",ingredient:"Yellow Chartreuse",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false}]},
  { name:"Mezcal Negroni", popularity:42, glass:"Rocks glass", method:"Stir",
    steps:"Stir all ingredients with ice 30 seconds. Strain over a large ice cube.",
    recipe:[{amount:"1 oz",ingredient:"Mezcal",is_garnish:false},{amount:"1 oz",ingredient:"Campari",is_garnish:false},{amount:"1 oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Tommy's Margarita", popularity:43, glass:"Rocks glass", method:"Shake",
    steps:"Shake with ice. Strain over ice in a rocks glass.",
    recipe:[{amount:"2 oz",ingredient:"100% agave tequila (blanco)",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"½ oz",ingredient:"Agave syrup",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Spicy Margarita", popularity:44, glass:"Rocks glass", method:"Shake",
    steps:"Muddle jalapeño in the shaker. Add tequila, triple sec, and lime with ice. Shake hard. Double strain into a salt-rimmed rocks glass over ice.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"1 oz",ingredient:"Triple sec",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"3 slices",ingredient:"Jalapeño (muddled)",is_garnish:false},{amount:"pinch",ingredient:"Salt (rim)",is_garnish:false}]},
  { name:"Penicillin", popularity:45, glass:"Rocks glass", method:"Shake",
    steps:"Shake Scotch, lemon, and honey-ginger syrup with ice. Strain over a large cube. Float Islay Scotch on top.",
    recipe:[{amount:"2 oz",ingredient:"Blended Scotch",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Honey-ginger syrup",is_garnish:false},{amount:"¼ oz",ingredient:"Islay Scotch (float)",is_garnish:false}]},
  { name:"Gold Rush", popularity:46, glass:"Rocks glass", method:"Shake",
    steps:"Shake all ingredients with ice. Strain over a large ice cube.",
    recipe:[{amount:"2 oz",ingredient:"Bourbon",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Honey syrup (2:1)",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Toronto", popularity:48, glass:"Coupe", method:"Stir",
    steps:"Stir all ingredients with ice 30 seconds. Strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Rye whiskey",is_garnish:false},{amount:"¼ oz",ingredient:"Fernet-Branca",is_garnish:false},{amount:"¼ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1 dash",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"New York Sour", popularity:49, glass:"Rocks glass", method:"Shake",
    steps:"Dry shake whiskey, lemon, syrup, and egg white. Add ice and shake again. Strain over ice. Float red wine by pouring gently over a spoon.",
    recipe:[{amount:"2 oz",ingredient:"Rye whiskey",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false},{amount:"½ oz",ingredient:"Dry red wine (float)",is_garnish:false}]},
  { name:"Vieux Carré", popularity:50, glass:"Rocks glass", method:"Stir",
    steps:"Stir all ingredients with ice 30 seconds. Strain over a large cube.",
    recipe:[{amount:"¾ oz",ingredient:"Rye whiskey",is_garnish:false},{amount:"¾ oz",ingredient:"Cognac",is_garnish:false},{amount:"¾ oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"1 tsp",ingredient:"Bénédictine",is_garnish:false},{amount:"2 dashes",ingredient:"Angostura bitters",is_garnish:false},{amount:"2 dashes",ingredient:"Peychaud's bitters",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Sazerac", popularity:51, glass:"Rocks glass", method:"Stir",
    steps:"Rinse a chilled rocks glass with absinthe, discard excess. Muddle sugar with bitters. Add rye and ice; stir until cold. Strain into the prepared glass without ice.",
    recipe:[{amount:"2 oz",ingredient:"Rye whiskey",is_garnish:false},{amount:"3 dashes",ingredient:"Peychaud's bitters",is_garnish:false},{amount:"1 cube",ingredient:"Sugar",is_garnish:false},{amount:"rinse",ingredient:"Absinthe",is_garnish:false}]},
  { name:"Corpse Reviver #2", popularity:52, glass:"Coupe", method:"Shake",
    steps:"Rinse a chilled coupe with absinthe. Shake remaining equal-parts ingredients with ice. Strain into the prepared glass.",
    recipe:[{amount:"¾ oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Triple sec / Cointreau",is_garnish:false},{amount:"¾ oz",ingredient:"Lillet Blanc",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"rinse",ingredient:"Absinthe",is_garnish:false},{amount:"1",ingredient:"Cherry",is_garnish:true}]},
  { name:"Hanky Panky", popularity:53, glass:"Coupe", method:"Stir",
    steps:"Stir all ingredients with ice 30 seconds. Strain into a chilled coupe.",
    recipe:[{amount:"1½ oz",ingredient:"Gin",is_garnish:false},{amount:"1½ oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"2 dashes",ingredient:"Fernet-Branca",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Bramble", popularity:54, glass:"Rocks glass", method:"Build",
    steps:"Shake gin, lemon, and syrup with ice. Strain over crushed ice. Drizzle crème de mûre over the top so it bleeds through.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"½ oz",ingredient:"Crème de mûre (drizzle)",is_garnish:false}]},
  { name:"Southside", popularity:55, glass:"Coupe", method:"Shake",
    steps:"Gently muddle mint with syrup. Add gin and lime with ice. Shake well. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"8 leaves",ingredient:"Fresh mint",is_garnish:false},{amount:"1 sprig",ingredient:"Mint",is_garnish:true}]},
  { name:"Irish Coffee", popularity:56, glass:"Irish coffee mug", method:"Build",
    steps:"Pre-warm the glass. Add whiskey and coffee, then stir in syrup. Float lightly whipped cream over the back of a spoon. Sip through the cream.",
    recipe:[{amount:"1½ oz",ingredient:"Irish whiskey",is_garnish:false},{amount:"3 oz",ingredient:"Hot strong coffee",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1 oz",ingredient:"Heavy cream (lightly whipped)",is_garnish:false}]},
  { name:"Fog Cutter", popularity:57, glass:"Tiki mug", method:"Shake",
    steps:"Shake all ingredients except sherry with ice. Pour into a tiki mug filled with crushed ice. Float sherry on top.",
    recipe:[{amount:"1½ oz",ingredient:"White rum",is_garnish:false},{amount:"½ oz",ingredient:"Gin",is_garnish:false},{amount:"½ oz",ingredient:"Brandy",is_garnish:false},{amount:"2 oz",ingredient:"Orange juice",is_garnish:false},{amount:"1 oz",ingredient:"Orgeat",is_garnish:false},{amount:"½ oz",ingredient:"Sherry (float)",is_garnish:false},{amount:"1 bouquet",ingredient:"Mint",is_garnish:true}]},
  { name:"Mai Tai", popularity:58, glass:"Tiki mug or rocks", method:"Shake",
    steps:"Shake all ingredients with crushed ice briefly. Pour (unstrained) into a tiki mug. Garnish with a mint bouquet and lime shell.",
    recipe:[{amount:"1 oz",ingredient:"Aged Jamaican rum",is_garnish:false},{amount:"1 oz",ingredient:"White rum",is_garnish:false},{amount:"½ oz",ingredient:"Orange Curaçao",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"½ oz",ingredient:"Orgeat",is_garnish:false},{amount:"1 bouquet",ingredient:"Mint",is_garnish:true}]},
  { name:"Painkiller", popularity:59, glass:"Tiki mug", method:"Shake",
    steps:"Shake all ingredients well with ice. Pour over ice in a tiki mug. Garnish with freshly grated nutmeg and a pineapple wedge.",
    recipe:[{amount:"2 oz",ingredient:"Dark rum (Pusser's)",is_garnish:false},{amount:"4 oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"1 oz",ingredient:"Orange juice",is_garnish:false},{amount:"1 oz",ingredient:"Coconut cream",is_garnish:false},{amount:"grating",ingredient:"Nutmeg",is_garnish:true}]},
  { name:"Ramos Gin Fizz", popularity:60, glass:"Highball", method:"Shake",
    steps:"Dry shake all ingredients except soda for 2 full minutes. Add ice and shake vigorously for another minute. Strain into a highball. Slowly pour soda water down a bar spoon to create the foam rise.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1 oz",ingredient:"Heavy cream",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false},{amount:"3 drops",ingredient:"Orange flower water",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false}]},
  { name:"El Diablo", popularity:63, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add tequila, crème de cassis, and lime juice. Top with ginger beer.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"½ oz",ingredient:"Crème de cassis",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"4 oz",ingredient:"Ginger beer",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Zombie", popularity:64, glass:"Zombie glass", method:"Shake",
    steps:"Shake all ingredients with crushed ice. Pour unstrained into a zombie glass. Add more crushed ice. Limit: 2 per customer.",
    recipe:[{amount:"1 oz",ingredient:"White rum",is_garnish:false},{amount:"1 oz",ingredient:"Dark rum",is_garnish:false},{amount:"1 oz",ingredient:"Aged rum",is_garnish:false},{amount:"½ oz",ingredient:"Apricot brandy",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"½ oz",ingredient:"Grenadine",is_garnish:false},{amount:"1 dash",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 bouquet",ingredient:"Mint",is_garnish:true}]},
  { name:"Oaxacan Old Fashioned", popularity:65, glass:"Rocks glass", method:"Stir",
    steps:"Stir all ingredients with ice 30 seconds. Strain over a large cube. Flame an orange peel over the glass and drop in.",
    recipe:[{amount:"1½ oz",ingredient:"Mezcal (joven)",is_garnish:false},{amount:"½ oz",ingredient:"Reposado tequila",is_garnish:false},{amount:"1 tsp",ingredient:"Agave syrup",is_garnish:false},{amount:"2 dashes",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Mint Julep", popularity:66, glass:"Julep tin", method:"Build",
    steps:"Gently muddle mint with syrup in the bottom of a julep tin. Pack tightly with crushed ice. Pour bourbon over the ice. Stir until the tin frosts.",
    recipe:[{amount:"2½ oz",ingredient:"Bourbon",is_garnish:false},{amount:"¼ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"8–10 leaves",ingredient:"Fresh mint",is_garnish:false},{amount:"1 bouquet",ingredient:"Mint",is_garnish:true}]},
  { name:"Amaretto Disaronno Sour", popularity:67, glass:"Rocks glass", method:"Shake",
    steps:"Dry shake all ingredients 15 seconds. Add ice and shake again. Strain over a large cube.",
    recipe:[{amount:"1½ oz",ingredient:"Amaretto (Disaronno)",is_garnish:false},{amount:"½ oz",ingredient:"Bourbon",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¼ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false},{amount:"1",ingredient:"Brandied cherry",is_garnish:true}]},
  { name:"Godfather", popularity:68, glass:"Rocks glass", method:"Build",
    steps:"Fill a rocks glass with ice. Add Scotch and amaretto. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Blended Scotch whisky",is_garnish:false},{amount:"¾ oz",ingredient:"Amaretto",is_garnish:false}]},
  { name:"Rusty Nail", popularity:69, glass:"Rocks glass", method:"Build",
    steps:"Fill a rocks glass with ice. Add Scotch and Drambuie. Stir briefly.",
    recipe:[{amount:"1½ oz",ingredient:"Blended Scotch whisky",is_garnish:false},{amount:"¾ oz",ingredient:"Drambuie",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Rob Roy", popularity:70, glass:"Coupe", method:"Stir",
    steps:"Stir all ingredients with ice 30 seconds. Strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Blended Scotch whisky",is_garnish:false},{amount:"1 oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"2 dashes",ingredient:"Angostura bitters",is_garnish:false},{amount:"1",ingredient:"Cherry",is_garnish:true}]},
  { name:"Blood and Sand", popularity:71, glass:"Coupe", method:"Shake",
    steps:"Shake equal parts with ice. Double strain into a chilled coupe.",
    recipe:[{amount:"¾ oz",ingredient:"Blended Scotch whisky",is_garnish:false},{amount:"¾ oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"¾ oz",ingredient:"Cherry Heering",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh orange juice",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Whiskey Mac", popularity:72, glass:"Rocks glass", method:"Build",
    steps:"Pour both ingredients into a rocks glass over ice. Stir briefly.",
    recipe:[{amount:"1½ oz",ingredient:"Blended Scotch whisky",is_garnish:false},{amount:"1½ oz",ingredient:"Ginger wine (Stone's)",is_garnish:false}]},
  { name:"Ward Eight", popularity:73, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients with ice. Strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Rye whiskey",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh orange juice",is_garnish:false},{amount:"½ tsp",ingredient:"Grenadine",is_garnish:false},{amount:"1",ingredient:"Cherry",is_garnish:true}]},
  { name:"Jack Rose", popularity:74, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients with ice. Strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Applejack or Calvados",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Grenadine (pomegranate)",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Scofflaw", popularity:75, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients with ice. Double strain into a chilled coupe.",
    recipe:[{amount:"1½ oz",ingredient:"Rye whiskey",is_garnish:false},{amount:"1 oz",ingredient:"Dry vermouth",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Grenadine",is_garnish:false},{amount:"2 dashes",ingredient:"Orange bitters",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Between the Sheets", popularity:76, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients with ice. Strain into a chilled coupe.",
    recipe:[{amount:"1 oz",ingredient:"Cognac",is_garnish:false},{amount:"1 oz",ingredient:"White rum",is_garnish:false},{amount:"1 oz",ingredient:"Triple sec",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Brandy Alexander", popularity:77, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients well with ice. Strain into a chilled coupe. Garnish with freshly grated nutmeg.",
    recipe:[{amount:"1 oz",ingredient:"Cognac",is_garnish:false},{amount:"1 oz",ingredient:"Crème de cacao (dark)",is_garnish:false},{amount:"1 oz",ingredient:"Heavy cream",is_garnish:false},{amount:"grating",ingredient:"Nutmeg",is_garnish:true}]},
  { name:"Stinger", popularity:78, glass:"Coupe", method:"Stir",
    steps:"Stir with ice 20 seconds. Strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Cognac",is_garnish:false},{amount:"¾ oz",ingredient:"White crème de menthe",is_garnish:false}]},
  { name:"Kir Royale", popularity:79, glass:"Champagne flute", method:"Build",
    steps:"Pour crème de cassis into a chilled flute. Gently top with champagne.",
    recipe:[{amount:"4 oz",ingredient:"Champagne or Crémant",is_garnish:false},{amount:"½ oz",ingredient:"Crème de cassis",is_garnish:false}]},
  { name:"Bellini", popularity:80, glass:"Champagne flute", method:"Build",
    steps:"Pour peach purée into a chilled flute. Slowly add prosecco. Stir once gently.",
    recipe:[{amount:"4 oz",ingredient:"Prosecco (chilled)",is_garnish:false},{amount:"2 oz",ingredient:"White peach purée",is_garnish:false}]},
  { name:"Mimosa", popularity:81, glass:"Champagne flute", method:"Build",
    steps:"Pour orange juice into a chilled flute. Top with champagne. Stir once gently.",
    recipe:[{amount:"3 oz",ingredient:"Champagne (or sparkling wine)",is_garnish:false},{amount:"3 oz",ingredient:"Fresh orange juice",is_garnish:false}]},
  { name:"Hugo Spritz", popularity:83, glass:"Wine glass", method:"Build",
    steps:"Fill a large wine glass with ice. Add elderflower liqueur, then prosecco, then soda. Add mint leaves and stir gently.",
    recipe:[{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Elderflower liqueur (St. Germain)",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"6 leaves",ingredient:"Fresh mint",is_garnish:false},{amount:"1 slice",ingredient:"Lime",is_garnish:true}]},
  { name:"Campari & Soda", popularity:84, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Campari. Top with soda water. Stir once. Garnish with an orange slice.",
    recipe:[{amount:"2 oz",ingredient:"Campari",is_garnish:false},{amount:"4 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Americano", popularity:85, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Campari and vermouth. Top with soda water and stir.",
    recipe:[{amount:"1½ oz",ingredient:"Campari",is_garnish:false},{amount:"1½ oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"½ wheel",ingredient:"Orange",is_garnish:true}]},
  { name:"Garibaldi", popularity:86, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Campari. Top with freshly squeezed, frothy orange juice.",
    recipe:[{amount:"2 oz",ingredient:"Campari",is_garnish:false},{amount:"4 oz",ingredient:"Fluffy orange juice",is_garnish:false},{amount:"½ wheel",ingredient:"Orange",is_garnish:true}]},
  { name:"Sbagliato", popularity:87, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Campari and vermouth. Top with prosecco and stir very gently.",
    recipe:[{amount:"1 oz",ingredient:"Campari",is_garnish:false},{amount:"1 oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"2 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Chartreuse Swizzle", popularity:89, glass:"Highball", method:"Swizzle",
    steps:"Pack a highball with crushed ice. Add all ingredients and swizzle vigorously. Top with more crushed ice.",
    recipe:[{amount:"1½ oz",ingredient:"Green Chartreuse",is_garnish:false},{amount:"1 oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"½ oz",ingredient:"Falernum",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 bouquet",ingredient:"Mint",is_garnish:true}]},
  { name:"Cucumber Gimlet", popularity:90, glass:"Coupe", method:"Shake",
    steps:"Muddle cucumber in shaker. Add remaining ingredients with ice. Shake well. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"3 slices",ingredient:"Cucumber (muddled)",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1 ribbon",ingredient:"Cucumber",is_garnish:true}]},
  { name:"Elderflower Collins", popularity:91, glass:"Highball", method:"Build",
    steps:"Shake gin, elderflower, and lemon with ice. Strain into an ice-filled highball. Top with soda water.",
    recipe:[{amount:"1½ oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Elderflower liqueur (St. Germain)",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"3 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Lemon",is_garnish:true}]},
  { name:"Pink Gin & Tonic", popularity:92, glass:"Copa glass", method:"Build",
    steps:"Fill a copa glass with ice. Add bitters to gin, stir briefly. Pour over ice and top with tonic.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"4 dashes",ingredient:"Angostura bitters",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"1 slice",ingredient:"Grapefruit",is_garnish:true}]},
  { name:"Sloe Gin Fizz", popularity:93, glass:"Highball", method:"Shake",
    steps:"Shake sloe gin, lemon, and syrup with ice. Strain into an ice-filled highball. Top with soda water.",
    recipe:[{amount:"2 oz",ingredient:"Sloe gin",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Lemon",is_garnish:true}]},
  { name:"Pisco Sour", popularity:94, glass:"Coupe", method:"Shake",
    steps:"Dry shake all ingredients 15 seconds. Add ice and shake again 10 seconds. Strain into a chilled coupe. Dot foam with bitters and swirl into a decorative pattern.",
    recipe:[{amount:"2 oz",ingredient:"Pisco",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false},{amount:"3 dashes",ingredient:"Angostura bitters (garnish)",is_garnish:false}]},
  { name:"Vodka Martini", popularity:97, glass:"Martini glass", method:"Stir",
    steps:"Stir vodka and vermouth with ice 30 seconds. Strain into a chilled martini glass.",
    recipe:[{amount:"2½ oz",ingredient:"Vodka",is_garnish:false},{amount:"½ oz",ingredient:"Dry vermouth",is_garnish:false},{amount:"2",ingredient:"Olives",is_garnish:true}]},
  { name:"Dirty Martini", popularity:98, glass:"Martini glass", method:"Stir",
    steps:"Stir gin, vermouth, and olive brine with ice 30 seconds. Strain into a chilled martini glass.",
    recipe:[{amount:"2 oz",ingredient:"Gin (or vodka)",is_garnish:false},{amount:"½ oz",ingredient:"Dry vermouth",is_garnish:false},{amount:"½ oz",ingredient:"Olive brine",is_garnish:false},{amount:"3",ingredient:"Olives",is_garnish:true}]},
  { name:"Vesper", popularity:100, glass:"Martini glass", method:"Shake",
    steps:"Shake all ingredients with ice until very cold. Strain into a chilled martini glass.",
    recipe:[{amount:"3 oz",ingredient:"Gin",is_garnish:false},{amount:"1 oz",ingredient:"Vodka",is_garnish:false},{amount:"½ oz",ingredient:"Lillet Blanc",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"B-52", popularity:102, glass:"Shot glass", method:"Build",
    steps:"Layer carefully in a shot glass: pour coffee liqueur first, then float Baileys over the back of a spoon, then float triple sec on top.",
    recipe:[{amount:"⅓ oz",ingredient:"Coffee liqueur (bottom)",is_garnish:false},{amount:"⅓ oz",ingredient:"Baileys Irish Cream (middle)",is_garnish:false},{amount:"⅓ oz",ingredient:"Triple sec / Grand Marnier (top)",is_garnish:false}]},
  { name:"Lemon Drop Shot", popularity:103, glass:"Shot glass", method:"Shake",
    steps:"Shake all ingredients with ice. Strain into a sugar-rimmed shot glass.",
    recipe:[{amount:"1½ oz",ingredient:"Citrus vodka",is_garnish:false},{amount:"½ oz",ingredient:"Triple sec",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"pinch",ingredient:"Sugar (rim)",is_garnish:false}]},
  { name:"Kamikaze", popularity:104, glass:"Shot glass", method:"Shake",
    steps:"Shake all ingredients with ice. Strain into a shot glass or chilled coupe.",
    recipe:[{amount:"1 oz",ingredient:"Vodka",is_garnish:false},{amount:"1 oz",ingredient:"Triple sec",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lime juice",is_garnish:false}]},
  { name:"Irish Mule", popularity:105, glass:"Copper mug", method:"Build",
    steps:"Fill a copper mug with ice. Add whiskey and lime juice. Top with ginger beer. Add a dash of bitters.",
    recipe:[{amount:"2 oz",ingredient:"Irish whiskey",is_garnish:false},{amount:"4 oz",ingredient:"Ginger beer",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 dash",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"White Lady", popularity:106, glass:"Coupe", method:"Shake",
    steps:"Dry shake all ingredients. Add ice and shake again. Double strain into a chilled coupe.",
    recipe:[{amount:"1½ oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Triple sec / Cointreau",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½",ingredient:"Egg white",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Smash", popularity:107, glass:"Rocks glass", method:"Shake",
    steps:"Muddle mint in the shaker. Add bourbon, lemon, and syrup with ice. Shake well. Double strain over crushed ice in a rocks glass.",
    recipe:[{amount:"2 oz",ingredient:"Bourbon",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"6 leaves",ingredient:"Fresh mint",is_garnish:false},{amount:"1 sprig",ingredient:"Mint",is_garnish:true}]},
  { name:"Highball", popularity:108, glass:"Highball", method:"Build",
    steps:"Fill a highball glass with ice. Add whisky. Top with very cold soda water, pouring down the side. Stir once from the bottom.",
    recipe:[{amount:"2 oz",ingredient:"Blended Scotch whisky",is_garnish:false},{amount:"4 oz",ingredient:"Chilled soda water",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Tequila Old Fashioned", popularity:109, glass:"Rocks glass", method:"Stir",
    steps:"Combine tequila, agave syrup, and bitters in a mixing glass with ice. Stir 25 seconds. Strain over a large cube. Express and drop in the orange peel.",
    recipe:[{amount:"2 oz",ingredient:"Reposado tequila",is_garnish:false},{amount:"1 tsp",ingredient:"Agave syrup",is_garnish:false},{amount:"2 dashes",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Rosita", popularity:110, glass:"Rocks glass", method:"Stir",
    steps:"Stir all ingredients with ice 30 seconds. Strain over a large ice cube.",
    recipe:[{amount:"1½ oz",ingredient:"Reposado tequila",is_garnish:false},{amount:"½ oz",ingredient:"Campari",is_garnish:false},{amount:"½ oz",ingredient:"Sweet vermouth",is_garnish:false},{amount:"½ oz",ingredient:"Dry vermouth",is_garnish:false},{amount:"1 dash",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Vodka Collins", popularity:111, glass:"Highball", method:"Build",
    steps:"Shake vodka, lemon, and syrup with ice. Strain into an ice-filled highball. Top with soda.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Lemon",is_garnish:true}]},
  { name:"Greyhound", popularity:112, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and grapefruit juice. Stir.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Fresh grapefruit juice",is_garnish:false},{amount:"1 slice",ingredient:"Grapefruit",is_garnish:true}]},
  { name:"Bay Breeze", popularity:113, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka, then cranberry juice, then pineapple juice. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Vodka",is_garnish:false},{amount:"2 oz",ingredient:"Cranberry juice",is_garnish:false},{amount:"2 oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"1 wedge",ingredient:"Pineapple",is_garnish:true}]},
  { name:"Madras", popularity:114, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and juices. Stir.",
    recipe:[{amount:"1½ oz",ingredient:"Vodka",is_garnish:false},{amount:"2 oz",ingredient:"Cranberry juice",is_garnish:false},{amount:"2 oz",ingredient:"Orange juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Espresso Negroni", popularity:115, glass:"Rocks glass", method:"Stir",
    steps:"Stir all ingredients with ice 20 seconds. Strain over a large cube.",
    recipe:[{amount:"1 oz",ingredient:"Vodka",is_garnish:false},{amount:"1 oz",ingredient:"Campari",is_garnish:false},{amount:"1 oz",ingredient:"Coffee liqueur",is_garnish:false},{amount:"1 oz",ingredient:"Chilled espresso",is_garnish:false},{amount:"3",ingredient:"Coffee beans",is_garnish:true}]},
  { name:"Rum Punch", popularity:116, glass:"Hurricane glass", method:"Build",
    steps:"Build over ice in a hurricane glass. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Dark rum",is_garnish:false},{amount:"2 oz",ingredient:"Orange juice",is_garnish:false},{amount:"2 oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"½ oz",ingredient:"Grenadine",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 dash",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Three Dots and a Dash", popularity:117, glass:"Tiki mug", method:"Shake",
    steps:"Shake everything except overproof rum with crushed ice. Pour into a tiki mug. Float overproof rum on top.",
    recipe:[{amount:"1½ oz",ingredient:"Aged rum",is_garnish:false},{amount:"½ oz",ingredient:"Overproof rum (float)",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh orange juice",is_garnish:false},{amount:"½ oz",ingredient:"Falernum",is_garnish:false},{amount:"½ oz",ingredient:"Honey syrup",is_garnish:false},{amount:"1 dash",ingredient:"Angostura bitters",is_garnish:false},{amount:"3 + 1",ingredient:"Cherries & pineapple (garnish)",is_garnish:true}]},
  { name:"Hemingway Daiquiri", popularity:118, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients vigorously with ice. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh grapefruit juice",is_garnish:false},{amount:"½ oz",ingredient:"Maraschino liqueur (Luxardo)",is_garnish:false},{amount:"1 wheel",ingredient:"Grapefruit",is_garnish:true}]},
  { name:"Floridita Daiquiri", popularity:119, glass:"Coupe", method:"Shake",
    steps:"Shake all ingredients with ice. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"½ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"¼ oz",ingredient:"Maraschino liqueur",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Kir", popularity:120, glass:"Wine glass", method:"Build",
    steps:"Pour crème de cassis into a wine glass. Top with cold white wine. Stir once.",
    recipe:[{amount:"4 oz",ingredient:"Dry white wine or Chablis",is_garnish:false},{amount:"½ oz",ingredient:"Crème de cassis",is_garnish:false}]},
  { name:"Lillet Spritz", popularity:121, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Lillet Blanc, then soda water. Express orange peel over top and drop in.",
    recipe:[{amount:"3 oz",ingredient:"Lillet Blanc",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Rosemary Gimlet", popularity:122, glass:"Coupe", method:"Shake",
    steps:"Make rosemary syrup: simmer 1:1 sugar and water with 2 rosemary sprigs, cool. Shake gin, lime, and syrup with ice. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Rosemary simple syrup",is_garnish:false},{amount:"1 sprig",ingredient:"Rosemary",is_garnish:true}]},
  { name:"Basil Smash", popularity:123, glass:"Rocks glass", method:"Shake",
    steps:"Muddle basil leaves in the shaker. Add gin, lemon, and syrup with ice. Shake vigorously. Double strain over ice in a rocks glass.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"8 leaves",ingredient:"Fresh basil",is_garnish:false},{amount:"1 leaf",ingredient:"Basil",is_garnish:true}]},
  { name:"Strawberry Daiquiri", popularity:124, glass:"Coupe", method:"Shake",
    steps:"Muddle strawberries in the shaker. Add rum, lime, and syrup with ice. Shake well. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"3–4",ingredient:"Fresh strawberries",is_garnish:false},{amount:"1",ingredient:"Strawberry",is_garnish:true}]},
  { name:"Blackberry Bramble Fizz", popularity:125, glass:"Highball", method:"Shake",
    steps:"Muddle blackberries with syrup. Add gin and lemon with ice; shake. Strain into an ice-filled highball. Top with soda and drizzle crème de mûre over the top.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"½ oz",ingredient:"Crème de mûre",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"3",ingredient:"Blackberries (muddled)",is_garnish:false},{amount:"3",ingredient:"Blackberries",is_garnish:true}]},
  { name:"Midori Sour", popularity:126, glass:"Rocks glass", method:"Shake",
    steps:"Dry shake all ingredients. Add ice and shake again. Strain over ice in a rocks glass.",
    recipe:[{amount:"1½ oz",ingredient:"Midori melon liqueur",is_garnish:false},{amount:"½ oz",ingredient:"Vodka",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"½",ingredient:"Egg white (optional)",is_garnish:false},{amount:"1",ingredient:"Maraschino cherry",is_garnish:true}]},
  { name:"Blue Lagoon", popularity:127, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and blue curaçao. Top with lemonade and lime juice. Stir.",
    recipe:[{amount:"1½ oz",ingredient:"Vodka",is_garnish:false},{amount:"1 oz",ingredient:"Blue Curaçao",is_garnish:false},{amount:"3 oz",ingredient:"Lemonade",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 slice",ingredient:"Lemon",is_garnish:true}]},
  { name:"Jungle Juice", popularity:128, glass:"Punch cup", method:"Build",
    steps:"Build over ice in a punch cup or highball. Stir to combine.",
    recipe:[{amount:"1 oz",ingredient:"Vodka",is_garnish:false},{amount:"½ oz",ingredient:"White rum",is_garnish:false},{amount:"½ oz",ingredient:"Triple sec",is_garnish:false},{amount:"2 oz",ingredient:"Orange juice",is_garnish:false},{amount:"1 oz",ingredient:"Cranberry juice",is_garnish:false},{amount:"2 oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"¼ oz",ingredient:"Grenadine",is_garnish:false}]},
  { name:"Aquavit Sour", popularity:129, glass:"Coupe", method:"Shake",
    steps:"Dry shake aquavit, lemon, syrup, and egg white 15 seconds. Add ice, shake again 10 seconds. Strain into a chilled coupe. Dot the foam with bitters.",
    recipe:[{amount:"2 oz",ingredient:"Aquavit",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"¾ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false},{amount:"2 dashes",ingredient:"Angostura bitters (garnish)",is_garnish:false}]},
  { name:"Cynar Spritz", popularity:130, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Cynar, then prosecco, then soda. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Cynar",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Suze & Tonic", popularity:131, glass:"Copa glass", method:"Build",
    steps:"Fill a copa glass with ice. Add Suze, then tonic. Stir once. Garnish with a long lemon peel spiral.",
    recipe:[{amount:"2 oz",ingredient:"Suze",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"1 long peel",ingredient:"Lemon",is_garnish:true}]},
  { name:"Pimm's Cup", popularity:132, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Pimm's and lemonade. Stir in the cucumber, strawberries, mint, and orange peel.",
    recipe:[{amount:"2 oz",ingredient:"Pimm's No. 1",is_garnish:false},{amount:"4 oz",ingredient:"Lemonade",is_garnish:false},{amount:"2 slices",ingredient:"Cucumber",is_garnish:false},{amount:"2",ingredient:"Strawberries (halved)",is_garnish:false},{amount:"3 leaves",ingredient:"Mint",is_garnish:false},{amount:"1 strip",ingredient:"Orange peel",is_garnish:false}]},
  { name:"Carajillo", popularity:133, glass:"Rocks glass", method:"Build",
    steps:"Pour Licor 43 into a rocks glass. Add a fresh hot espresso shot on top. Stir once. Serve immediately.",
    recipe:[{amount:"1½ oz",ingredient:"Licor 43",is_garnish:false},{amount:"1 oz",ingredient:"Hot espresso",is_garnish:false}]},
  { name:"Coconut Mojito", popularity:134, glass:"Highball", method:"Build",
    steps:"Gently muddle mint with lime and syrup. Add rum, coconut water, and ice. Stir to combine. Top with soda.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"2 oz",ingredient:"Coconut water",is_garnish:false},{amount:"¾ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"½ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"8 leaves",ingredient:"Fresh mint",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 sprig",ingredient:"Mint",is_garnish:true}]},
  { name:"Coco Loco", popularity:135, glass:"Highball", method:"Build",
    steps:"Shake all ingredients with ice. Strain into a highball filled with crushed ice.",
    recipe:[{amount:"1½ oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"1 oz",ingredient:"Coconut cream",is_garnish:false},{amount:"3 oz",ingredient:"Pineapple juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Pineapple",is_garnish:true}]},
  { name:"Apple Sour", popularity:136, glass:"Coupe", method:"Shake",
    steps:"Dry shake all ingredients 15 seconds. Add ice and shake again. Double strain into a chilled coupe.",
    recipe:[{amount:"2 oz",ingredient:"Bourbon",is_garnish:false},{amount:"1 oz",ingredient:"Apple juice (cloudy)",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"½ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1",ingredient:"Egg white",is_garnish:false},{amount:"1 thin slice",ingredient:"Apple",is_garnish:true}]},
  { name:"Autumn Harvest", popularity:137, glass:"Rocks glass", method:"Stir",
    steps:"Combine all ingredients in a mixing glass with ice. Stir 25 seconds. Strain over a large cube.",
    recipe:[{amount:"2 oz",ingredient:"Bourbon",is_garnish:false},{amount:"1 oz",ingredient:"Apple cider",is_garnish:false},{amount:"½ oz",ingredient:"Cinnamon syrup",is_garnish:false},{amount:"2 dashes",ingredient:"Angostura bitters",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Chambord Royale", popularity:138, glass:"Champagne flute", method:"Build",
    steps:"Pour Chambord and lemon juice into a chilled flute. Top with champagne. Stir once very gently.",
    recipe:[{amount:"½ oz",ingredient:"Chambord",is_garnish:false},{amount:"4 oz",ingredient:"Champagne (chilled)",is_garnish:false},{amount:"¼ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"1",ingredient:"Raspberry",is_garnish:true}]},
  { name:"Kir Normand", popularity:139, glass:"Wine glass", method:"Build",
    steps:"Pour crème de cassis into a wine glass. Top gently with cold sparkling cider. Stir once.",
    recipe:[{amount:"4 oz",ingredient:"Dry sparkling apple cider",is_garnish:false},{amount:"½ oz",ingredient:"Crème de cassis",is_garnish:false},{amount:"1 thin slice",ingredient:"Apple",is_garnish:true}]},
  { name:"Vodka Tonic", popularity:140, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka, then pour tonic slowly down the side. Squeeze in lime wedge and drop in. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Rum & Soda", popularity:141, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add rum and lime juice. Top with soda water. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"4 oz",ingredient:"Soda water",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Tequila Tonic", popularity:142, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add tequila and lime juice. Top with tonic water slowly. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Mezcal Tonic", popularity:143, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add mezcal and lime juice. Top with tonic. Express the orange peel over the top and drop in.",
    recipe:[{amount:"2 oz",ingredient:"Mezcal",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Bourbon & Ginger", popularity:144, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add bourbon and lemon juice. Top with ginger ale. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Bourbon",is_garnish:false},{amount:"4 oz",ingredient:"Ginger ale",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lemon",is_garnish:true}]},
  { name:"Scotch & Soda", popularity:145, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Scotch. Pour soda water slowly down the side. Stir once from the bottom.",
    recipe:[{amount:"2 oz",ingredient:"Blended Scotch whisky",is_garnish:false},{amount:"4 oz",ingredient:"Chilled soda water",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Rum & Tonic", popularity:146, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add rum, then tonic slowly. Squeeze in lime and drop in. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"White rum",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Whiskey & Cola", popularity:147, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add bourbon, then cola. Add a squeeze of lime. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Bourbon",is_garnish:false},{amount:"4 oz",ingredient:"Cola",is_garnish:false},{amount:"¼ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Gin & Soda", popularity:148, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add gin and lime juice. Top with soda water. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"4 oz",ingredient:"Soda water",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Campari Tonic", popularity:149, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Campari. Top with tonic slowly. Express and drop in the orange peel.",
    recipe:[{amount:"1½ oz",ingredient:"Campari",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Aperol Tonic", popularity:150, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Aperol and lime juice. Top with tonic. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Aperol",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"¼ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Elderflower Tonic", popularity:151, glass:"Copa glass", method:"Build",
    steps:"Fill a copa glass with ice. Add elderflower liqueur and gin. Top with tonic. Stir gently.",
    recipe:[{amount:"1 oz",ingredient:"Elderflower liqueur (St. Germain)",is_garnish:false},{amount:"1 oz",ingredient:"Gin",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"2 slices",ingredient:"Cucumber",is_garnish:false},{amount:"1 sprig",ingredient:"Mint",is_garnish:true}]},
  { name:"Cognac & Soda", popularity:152, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add cognac. Pour soda water slowly down the glass. Express the lemon peel over the top and drop in.",
    recipe:[{amount:"2 oz",ingredient:"Cognac",is_garnish:false},{amount:"3 oz",ingredient:"Chilled soda water",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Rye & Ginger", popularity:153, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add rye and lemon juice. Top with ginger ale. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Rye whiskey",is_garnish:false},{amount:"4 oz",ingredient:"Ginger ale",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lemon juice",is_garnish:false},{amount:"1 wheel",ingredient:"Lemon",is_garnish:true}]},
  { name:"Pisco & Tonic", popularity:154, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add pisco and lime juice. Top with tonic. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Pisco",is_garnish:false},{amount:"4 oz",ingredient:"Tonic water",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Irish Whiskey & Ginger", popularity:155, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add whiskey and lime juice. Top with ginger ale. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Irish whiskey",is_garnish:false},{amount:"4 oz",ingredient:"Ginger ale",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Vodka & Cranberry", popularity:156, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka, cranberry juice, and lime juice. Stir.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Cranberry juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Mezcal & Coke", popularity:157, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add mezcal, then cola. Squeeze in a little lime. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Mezcal",is_garnish:false},{amount:"4 oz",ingredient:"Cola",is_garnish:false},{amount:"¼ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Amaro & Soda", popularity:158, glass:"Rocks glass", method:"Build",
    steps:"Fill a rocks glass with ice. Add amaro and soda water. Stir gently. Express the orange peel over the top and drop in.",
    recipe:[{amount:"2 oz",ingredient:"Amaro Nonino",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Fernet & Ginger", popularity:159, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Fernet-Branca and lime juice. Top with ginger ale. Stir once.",
    recipe:[{amount:"1½ oz",ingredient:"Fernet-Branca",is_garnish:false},{amount:"4 oz",ingredient:"Ginger ale",is_garnish:false},{amount:"¼ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Ranch Water", popularity:160, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add tequila and lime juice. Top with sparkling mineral water. Drop in a lime wedge.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"4 oz",ingredient:"Sparkling mineral water (Topo Chico)",is_garnish:false},{amount:"1 wedge",ingredient:"Lime",is_garnish:true}]},
  { name:"Spicy Ranch Water", popularity:161, glass:"Highball", method:"Build",
    steps:"Muddle jalapeño slices in the bottom of a highball. Add ice, tequila, and lime juice. Top with sparkling mineral water. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"2 slices",ingredient:"Fresh jalapeño",is_garnish:false},{amount:"4 oz",ingredient:"Sparkling mineral water",is_garnish:false},{amount:"1 wheel",ingredient:"Jalapeño",is_garnish:true}]},
  { name:"Mezcal Ranch Water", popularity:162, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add mezcal and lime juice. Top with sparkling mineral water. Stir once gently.",
    recipe:[{amount:"2 oz",ingredient:"Mezcal",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"4 oz",ingredient:"Sparkling mineral water",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Vodka Ranch Water", popularity:163, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and lime juice. Top with sparkling mineral water. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"4 oz",ingredient:"Sparkling mineral water",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Gin Ranch Water", popularity:164, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add gin, lime juice, and cucumber slices. Top with sparkling mineral water. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"4 oz",ingredient:"Sparkling mineral water",is_garnish:false},{amount:"2 slices",ingredient:"Cucumber",is_garnish:false},{amount:"1 ribbon",ingredient:"Cucumber",is_garnish:true}]},
  { name:"Tequila Soda", popularity:165, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add tequila and lime juice. Top with soda water. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"4 oz",ingredient:"Soda water",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Hard Seltzer Style", popularity:166, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka, lime juice, and simple syrup. Top with sparkling mineral water. Stir once gently.",
    recipe:[{amount:"1½ oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Sparkling mineral water",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"¼ oz",ingredient:"Simple syrup",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Paloma Mineral", popularity:167, glass:"Highball", method:"Build",
    steps:"Salt-rim a highball. Fill with ice. Add tequila, grapefruit juice, lime, and salt. Top with sparkling mineral water.",
    recipe:[{amount:"2 oz",ingredient:"Tequila (blanco)",is_garnish:false},{amount:"2 oz",ingredient:"Fresh grapefruit juice",is_garnish:false},{amount:"½ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"pinch",ingredient:"Salt",is_garnish:false},{amount:"2 oz",ingredient:"Sparkling mineral water",is_garnish:false},{amount:"1 wedge",ingredient:"Grapefruit",is_garnish:true}]},
  { name:"Cointreau Fizz", popularity:168, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Cointreau and lime juice. Top with sparkling mineral water. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Cointreau / Triple sec",is_garnish:false},{amount:"1 oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"3 oz",ingredient:"Sparkling mineral water",is_garnish:false},{amount:"1 wheel",ingredient:"Lime",is_garnish:true}]},
  { name:"Aperol & Mineral", popularity:169, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Aperol. Top with sparkling mineral water. Express orange peel over the top and drop in. Stir once gently.",
    recipe:[{amount:"2 oz",ingredient:"Aperol",is_garnish:false},{amount:"4 oz",ingredient:"Sparkling mineral water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Campari Spritz", popularity:170, glass:"Wine glass", method:"Build",
    steps:"Fill a large wine glass with ice. Pour prosecco, then Campari, then a splash of soda water. Stir once very gently.",
    recipe:[{amount:"2 oz",ingredient:"Campari",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Suze Spritz", popularity:173, glass:"Wine glass", method:"Build",
    steps:"Fill a large wine glass with ice. Add Suze, then prosecco, then soda. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Suze",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Fernet Spritz", popularity:174, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Fernet-Branca, then prosecco, then soda. Stir once.",
    recipe:[{amount:"1½ oz",ingredient:"Fernet-Branca",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Amaro Spritz", popularity:175, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Amaro Nonino, then prosecco, then soda. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Amaro Nonino",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Lillet Blanc Spritz", popularity:176, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Lillet Blanc, then prosecco, then soda. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Lillet Blanc",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Elderflower Spritz", popularity:177, glass:"Wine glass", method:"Build",
    steps:"Fill a large wine glass with ice. Add elderflower liqueur, then prosecco, then soda. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Elderflower liqueur (St. Germain)",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"2 slices",ingredient:"Cucumber",is_garnish:false},{amount:"1 sprig",ingredient:"Mint",is_garnish:true}]},
  { name:"Chambord Spritz", popularity:178, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Chambord, then prosecco, then soda. Stir gently.",
    recipe:[{amount:"1 oz",ingredient:"Chambord",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1",ingredient:"Raspberry",is_garnish:true}]},
  { name:"Green Chartreuse Spritz", popularity:179, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Chartreuse, then prosecco, then soda. Stir once.",
    recipe:[{amount:"1 oz",ingredient:"Green Chartreuse",is_garnish:false},{amount:"3 oz",ingredient:"Prosecco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Lemon peel",is_garnish:true}]},
  { name:"Cava Spritz", popularity:180, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Pour Cava, then Aperol, then soda. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Aperol",is_garnish:false},{amount:"3 oz",ingredient:"Cava",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Rosé Spritz", popularity:181, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Aperol, then sparkling rosé, then soda. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Aperol",is_garnish:false},{amount:"3 oz",ingredient:"Sparkling rosé",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Lambrusco Spritz", popularity:182, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Add Campari, then Lambrusco, then soda. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Campari",is_garnish:false},{amount:"3 oz",ingredient:"Lambrusco",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
  { name:"Campari & Bitter Lemon", popularity:183, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add Campari. Top with bitter lemon. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Campari",is_garnish:false},{amount:"4 oz",ingredient:"Bitter lemon",is_garnish:false},{amount:"1 slice",ingredient:"Lemon",is_garnish:true}]},
  { name:"Gin & Bitter Lemon", popularity:184, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add gin and lime juice. Top with bitter lemon. Stir once.",
    recipe:[{amount:"2 oz",ingredient:"Gin",is_garnish:false},{amount:"4 oz",ingredient:"Bitter lemon",is_garnish:false},{amount:"¼ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 slice",ingredient:"Lemon",is_garnish:true}]},
  { name:"Vodka & Bitter Lemon", popularity:185, glass:"Highball", method:"Build",
    steps:"Fill a highball with ice. Add vodka and lime juice. Top with bitter lemon. Stir gently.",
    recipe:[{amount:"2 oz",ingredient:"Vodka",is_garnish:false},{amount:"4 oz",ingredient:"Bitter lemon",is_garnish:false},{amount:"¼ oz",ingredient:"Fresh lime juice",is_garnish:false},{amount:"1 wheel",ingredient:"Lemon",is_garnish:true}]},
  { name:"White Wine Spritz", popularity:186, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Pour white wine, then soda water. Stir once.",
    recipe:[{amount:"4 oz",ingredient:"Dry white wine (chilled)",is_garnish:false},{amount:"2 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Lemon",is_garnish:true}]},
  { name:"Aperol White Wine Spritz", popularity:188, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Pour white wine, then Aperol, then soda. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Aperol",is_garnish:false},{amount:"3 oz",ingredient:"Dry white wine",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 slice",ingredient:"Orange",is_garnish:true}]},
  { name:"Campari White Wine Spritz", popularity:189, glass:"Wine glass", method:"Build",
    steps:"Fill a wine glass with ice. Pour white wine, then Campari, then soda. Stir gently.",
    recipe:[{amount:"1½ oz",ingredient:"Campari",is_garnish:false},{amount:"3 oz",ingredient:"Dry white wine",is_garnish:false},{amount:"1 oz",ingredient:"Soda water",is_garnish:false},{amount:"1 twist",ingredient:"Orange peel",is_garnish:true}]},
];
